#!/bin/bash
#PBS -N my_job
#PBS -l nodes=3:ppn=24
#PBS -j oe
#PBS -l walltime=00:20:00
#PBS -q parallel01
#PBS -e my_job.$PBS_JOBID.err
#PBS -o my_job.$PBS_JOBID.out
#PBS -V

cd $PBS_O_WORKDIR
NP=`cat $PBS_NODEFILE|wc -l`

module load compiler/gcc/4.4
module load mpi/openmpi/1.6.5
module load netcdf/4.1.3
module load fftw/3.3.3
$MPI_ROOT/bin/mpirun -machinefile  $PBS_NODEFILE -n 64 -x LD_LIBRARY_PATH  elm_pb_rf 
