# Makefile for example codes
# Works in the same way as the root Makefile

BOUT_TOP	= ..

DIRS		= advect1d rayleigh-taylor drift-instability \
                  lapd-drift orszag-tang interchange-instability \
                  rb-tokamak shear-alfven-wave uedge-benchmark	\
		  elm-pb elm-pb-4fields elm-pb-5fields elm-pb-4fields-HHM \
		  elm-pb-3fields-P0 \
		  glf1-0 glf2-0 glf3-0-0.1 glfetg3-1 glf-landau-HP3+0

include $(BOUT_TOP)/make.config
