
BOUT_TOP = ../..

DIRS            = impls data
SOURCEC		= difops.cxx interpolation.cxx mesh.cxx boundary_standard.cxx boundary_factory.cxx boundary_region.cxx meshfactory.cxx surfaceiter.cxx fv_ops.cxx integrops.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.hxx)
TARGET		= lib

include $(BOUT_TOP)/make.config
